## Travis CI Integration
language: csharp
solution: NitroDebugger.sln

# In this way it does not override install
after_install:
  - sudo apt-get install nunit-console

script:
  - xbuild NitroDebugger.sln
  - nunit-console NitroDebugger.UnitTests/bin/Debug/NitroDebugger.UnitTests.dll
