## Travis CI Integration
language: csharp
solution: NitroDebugger.sln

# Handle git submodules yourself
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

# In this way it does not override install
before_script:
  - sudo apt-get install nunit-console

script:
  - xbuild NitroDebugger.sln
  - nunit-console NitroDebugger.UnitTests/bin/Debug/NitroDebugger.UnitTests.dll
