## Travis CI Integration
language: c

install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - sudo add-apt-repository -y "deb http://download.mono-project.com/repo/debian wheezy main"
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install mono-devel nunit-console
  - wget http://nuget.org/nuget.exe -O ./.nuget/NuGet.exe
  - chmod a+x ./.nuget/NuGet.exe
  - mozroots --import --sync
script:
  - xbuild NitroDebugger.sln
  - nunit-console NitroDebugger.UnitTests/bin/Debug/NitroDebugger.UnitTests.dll

env:
 global:
  - EnableNuGetPackageRestore=true
